# Make rules for configuration files.
#
# $Id$

CFG		= kernel-$(VERSION)

CONFIGFILES	= \
	$(CFG)-armv7hnl.config

PLATFORMS	= odroid
TEMPFILES	= $(addprefix temp-, $(PLATFORMS))

configs: $(CONFIGFILES)
	@rm -f kernel-*-config
	@rm -f $(TEMPFILES)
	@rm -f temp-fedora temp-odroid

# Augment the clean target to clean up our own cruft
clean ::
	@rm -fv $(CONFIGFILES) $(TEMPFILES) temp-generic kernel-$(VERSION)*config

temp-fedora: config-fedora
	cat $^ > temp-fedora

temp-odroid: temp-fedora arch/arm/configs/odroidu_defconfig
	perl merge.pl $^ > $@

$(CFG)-armv7hnl.config: /dev/null temp-odroid
	perl merge.pl $^ arm > $@
